### ISSUE TITLE
FileNotFoundError: 'frozen_models/pytorch_i3d/models/rgb_imagenet.pt'

### ISSUE THREAD

**Issue by taipingeric** [levyisthebest/ECHOPulse_Prelease#1]
Hi, 
1. Is there any **rgb_imagenet.pt** file to download? 
I can't find it in huggingface hub. Thanks~

2. I can't find the **st_mem.yaml** and **./st_mem/pretrain/encoder.pth** file

**Comment by levyisthebest** [comment]
1. https://huggingface.co/datasets/Levi980623/ECHOTest/tree/main/frozen_models Thanks for your reminder, I have updated the models on the huggingface.
2. st_mem.yaml is in the STMEM/configs/pretrain/st_mem.yaml folder and encoder.pth is uploaded on https://huggingface.co/datasets/Levi980623/ECHOTest/tree/main called st_mem_vit_base_encoder.pth. Please have a try
Thanks for the reminder. I neglected to modify the .gitignore when I uploaded it. You can try it now. If you have any questions, you can contact me at yili6@mgh.harvard.edu in case I didn’t see it.
